# StatsD to Prometheus Mapping Configuration for PDF Converter Pipeline
# Маппинг StatsD метрик в метрики Prometheus

# Метрики конвейера PDF
mappings:
  # Основные метрики конвейера
  - match: "pdf.pipeline.*.completed"
    name: "pdf_pipeline_completed_total"
    labels:
      status: "$1"
    help: "Total number of completed PDF processing pipelines"

  - match: "pdf.pipeline.*.duration"
    name: "pdf_pipeline_duration_seconds"
    labels:
      stage: "$1"
    help: "Duration of PDF pipeline stages in seconds"

  # Метрики DAG
  - match: "pdf.dag.*.*.duration"
    name: "pdf_dag_duration_seconds"
    labels:
      dag_name: "$1"
      task_name: "$2"
    help: "Duration of individual DAG tasks in seconds"

  - match: "pdf.dag.*.tasks.active"
    name: "pdf_active_tasks_total"
    labels:
      dag_name: "$1"
    help: "Number of currently active tasks per DAG"

  - match: "pdf.dag.*.tasks.completed"
    name: "pdf_tasks_completed_total"
    labels:
      dag_name: "$1"
    help: "Total number of completed tasks per DAG"

  - match: "pdf.dag.*.errors.*"
    name: "pdf_pipeline_errors_total"
    labels:
      stage: "$1"
      error_type: "$2"
    help: "Total number of errors by pipeline stage and type"

  # Метрики качества (Quality Assurance)
  - match: "pdf.quality.score.*"
    name: "pdf_quality_score"
    labels:
      validation_level: "$1"
    help: "Quality scores from 5-level validation system"

  - match: "pdf.quality.*.corrections"
    name: "pdf_quality_corrections_total"
    labels:
      validation_level: "$1"
    help: "Number of corrections applied by validation level"

  - match: "pdf.quality.overall.score"
    name: "pdf_quality_overall_score"
    help: "Overall quality score for processed documents"

  # Метрики vLLM
  - match: "vllm.requests.*.duration"
    name: "vllm_request_duration_seconds"
    labels:
      operation: "$1"
    help: "Duration of vLLM requests in seconds"

  - match: "vllm.requests.*"
    name: "vllm_requests_total"
    labels:
      operation: "$1"
    help: "Total number of vLLM requests by operation"

  - match: "vllm.model.*.tokens.input"
    name: "vllm_input_tokens_total"
    labels:
      model: "$1"
    help: "Total input tokens processed by vLLM models"

  - match: "vllm.model.*.tokens.output"
    name: "vllm_output_tokens_total"
    labels:
      model: "$1"
    help: "Total output tokens generated by vLLM models"

  - match: "vllm.gpu.utilization"
    name: "vllm_gpu_utilization_percent"
    help: "GPU utilization percentage for vLLM"

  # Метрики Document Processor
  - match: "docprocessor.*.requests"
    name: "docprocessor_requests_total"
    labels:
      component: "$1"
    help: "Total requests to document processor components"

  - match: "docprocessor.ocr.*.accuracy"
    name: "docprocessor_ocr_accuracy_percent"
    labels:
      engine: "$1"
    help: "OCR accuracy percentage by engine"

  - match: "docprocessor.*.processing.time"
    name: "docprocessor_processing_seconds"
    labels:
      component: "$1"
    help: "Processing time for document processor components"

  # Метрики переводчика
  - match: "translator.*.requests"
    name: "translator_requests_total"
    labels:
      target_language: "$1"
    help: "Translation requests by target language"

  - match: "translator.*.quality.score"
    name: "translator_quality_score"
    labels:
      target_language: "$1"
    help: "Translation quality scores by language"

  # Файловые метрики
  - match: "pdf.files.processed.*"
    name: "pdf_files_processed_total"
    labels:
      target_language: "$1"
    help: "Total number of processed files by language"

  - match: "pdf.files.size.bytes"
    name: "pdf_file_size_bytes"
    help: "Size of processed PDF files in bytes"

  - match: "pdf.files.pages"
    name: "pdf_file_pages_total"
    help: "Number of pages in processed PDF files"

  # Метрики Flask API
  - match: "flask.api.*.requests"
    name: "flask_api_requests_total"
    labels:
      endpoint: "$1"
    help: "Total API requests by endpoint"

  - match: "flask.api.*.duration"
    name: "flask_api_duration_seconds"
    labels:
      endpoint: "$1"
    help: "API request duration by endpoint"

  - match: "flask.api.*.errors.*"
    name: "flask_api_errors_total"
    labels:
      endpoint: "$1"
      error_code: "$2"
    help: "API errors by endpoint and status code"

  # Batch processing метрики
  - match: "pdf.batch.*.files"
    name: "pdf_batch_files_total"
    labels:
      batch_id: "$1"
    help: "Number of files in batch processing"

  - match: "pdf.batch.*.duration"
    name: "pdf_batch_duration_seconds"
    labels:
      batch_id: "$1"
    help: "Duration of batch processing"

  # Системные метрики
  - match: "system.*.cpu.usage"
    name: "system_cpu_usage_percent"
    labels:
      service: "$1"
    help: "CPU usage by service"

  - match: "system.*.memory.usage"
    name: "system_memory_usage_bytes"
    labels:
      service: "$1"
    help: "Memory usage by service"

  - match: "system.*.disk.usage"
    name: "system_disk_usage_bytes"
    labels:
      service: "$1"
    help: "Disk usage by service"

# Глобальные настройки таймеров
timer_type: histogram
buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]

# Дефолт для неопознанных метрик
defaults:
  timer_type: histogram
  buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
  match_type: glob